//CODE BY GEMINI WHICH RUNS USING LIMITS FEATURE

#include <iostream>
#include <limits> // Required for std::numeric_limits

int main() {
    double radius;
    double PI = 3.14159;
    double AREA;

    // First cout statement
    std::cout << "WELCOME TO RADIUS OF CIRCLE CALCULATOR (Press Enter to continue)";

    // This line will pause the program until the user presses Enter.
    // std::cin.ignore() will consume the newline character generated by the Enter key.
    std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');

    // Next cout statement, which executes after Enter is pressed
    std::cout << "Enter Radius of circle: ";

    // The rest of your code executes
    std::cin >> radius;
    AREA = radius * PI * radius;
    std::cout << "Area of given circle is: " << AREA << " sq.meters" << std::endl;

    return 0;
}




//MY CODE WHICH I WROTE:

// #include <iostream>
// #include <limits>
// using namespace std;

// int main(){
// double radius;;
// double PI= 3.14159;
// double AREA;

// cout<<"WELCOME TO RADIUS OF CIRCLE CALCULATOR (please click enter)";
// std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
// cout<<"Enter Radius of circle: ";
// cin>>radius;
// AREA= radius*PI*radius;
// cout<<"Area of given circle is: "<<AREA<<" sq.meters"<<endl;

// return 0;
// }